task: gan
task_name: vanila_gan_cifar10_weights_init

model:
  type: vanila_gan
  img_size: 32
  in_channels: 3 # RGB:3 / Grayscale:1
  latent_dim: 100
  activation: tanh

dataset:
  name: cifar10
  root: ./data

train:
  epochs: 100
  batch_size: 128
  num_workers: 4
  learning_rate: 0.0002
  loss_fn: bce
  optimizer: adam
  beta1: 0.5
  beta2: 0.999
