task: diffusion

model:
  type: ddpm
  img_size: 32
  in_channels: 3 # RGB:3 / Grayscale:1
  num_res_blocks: 2
  dim: 128
  dim_mults: [1, 2, 2, 2]
  attn_layers: [16]
  dropout: 0.1

dataset:
  name: cifar10
  root: ./data

train:
  epochs: 800
  batch_size: 128
  num_workers: 4
  learning_rate: 0.0002
  loss_fn: mse
  optimizer: adam
  ema: true
  ema_decay: 0.9999

diffusion:
  num_timesteps: 1000
  beta_start: 0.0001
  beta_end: 0.02
  variance_type: fixed_small
