task: vae

model:
  type: vanila_vae
  img_size: 32
  in_channels: 3 # RGB:3 / Grayscale:1
  latent_dim: 128
  activation: tanh

dataset:
  name: cifar10
  root: ./data

train:
  epochs: 100
  batch_size: 128
  num_workers: 4
  learning_rate: 1e-3
  weight_decay: 1e-5
  loss_fn: mse
  optimizer: adam

